### ISSUE TITLE
Tem como usar essa dll com visual dataflex?

### ISSUE THREAD

**Issue by leauad** [tiagopsilva/sha256sign#1]

**Comment by tiagopsilva** [comment]
Não conheço Visual DataFlex.
Mas se com ele for possível utilizar dll´s como as escritas em C e Delphi, então sim.

**Comment by leauad** [comment]
Não consegui abrir o projeto com Visual Studio 2008.Qual versão foi utilizada?

**Comment by tiagopsilva** [comment]
VS 2013 Já deve abrir, mas utilizei a 2017.

**Comment by leauad** [comment]
Bom dia Tiago.Não estou conseguindo usar a dll.Essa DLL que ta dentro do exemplo em Delphi pode utilizar ela ? Qual retorno da funcao SignFileWithSHA256Ansi ??

**Comment by tiagopsilva** [comment]
@leauad, eu não tinha certeza se era a última versão compilada da DLL que estava na pasta de exemplo então acabei de fazer um _commit_ dela e agora tenho certeza. Pode usar.
`SignFileWithSHA256Ansi` não é uma função, é uma _procedure_ e portanto não retorna valor.
O procedimento deve ser efetuado da seguinte forma:
1. Gere o arquivo xml pela sua aplicação e salve em disco;
2. Execute o método da DLL passando o path completo do arquivo XML no computador para a DLL;
3. O arquivo agora estará assinado e você poderá recarregá-lo para dentro do sistema.

Houve formas de se trabalhar com ela sem precisar ser com arquivo em disco, porém foram encontrados alguns problemas em algumas versões antigas do Delphi, inclusive em algumas versões novas também, e esses erros poderiam com certeza acontecer em outras linguagens também. Por isso, no momento, ela está trabalhando com o arquivo em disco.

Me relataram que funciona melhor se não passar a senha (PIN) do certificado.
**Você está usando certificado A3?**

Sucesso com sua implementação!
