### ISSUE TITLE
Foi escrita em qual versão do .NET?

### ISSUE THREAD

**Issue by leauad** [tiagopsilva/sha256sign#2]

**Comment by tiagopsilva** [comment]
@leauad, ela foi inicialmente escrita com o .NET 4.0, e por isso usava uma DLL para a criptografia,
mas hoje está com o .NET 4.5.

Pois, com a necessidade de usar o protocolo TLS 1.2 para estabelecer comunicação com os WebServices do e-Social, as máquinas já precisam ter instalado, se não me engano, o .NET 4.6.2. Entre outras configurações para a comunicação ocorrer com sucesso.

Logo, meu desejo de manter compatibilidade com o Windows XP já não era mais possível, já que o XP instala no máximo o .NET 4.0 (isso se for instalado o Service Pack 3).

Eu fiz uma pergunta para você anteriormente e acabei fechando a issue. 
**Você está tentando essa DLL para assinar os documento com certificado A3?**

**Comment by leauad** [comment]
Em um cliente sim , será A3 , porem outros 2 eles possuem A1.Meu foco não é Folha de Pgto , mas fiz tempos atras e agora vou ter que me virar pra enviar isso.Enforcado aqui..kkk.Acho que meu sistema não vai dar certo com essa dll , até agora nao consegui , ele diz que nao acha a procedure.Na verdade todas as dll que utilizo até hoje são funções , em Visual Dataflex to apanhando pra fazer isso funcionar.

**Comment by tiagopsilva** [comment]
**Essa DLL funciona para certificado A3.**
Me envie um e-mail que então te enviarei o exec compilado em Delphi para que você possa testar em seu ambiente.
